### ISSUE TITLE
TODO: `oui` branch

### ISSUE THREAD

**Issue by jonathantneal** [tabvengers/spicy-sections#61]
Here are some goals I’m hoping to accomplish, next steps for the spicy-sections script, after some discussion with @bkardell.

- create new `oui` branch with a `oui-panelset.js` script:
  - [x] use `<oui-panelset>` instead of `<spicy-sections>`.
  - [x] drop `class RegionSet extends MediaAffordancesElement {}`.
  - [x] use `class OUIPanelset extends HTMLElement {}`.
  - [x] drop any "living" IDL-like behavior from `[affordance]` HTML attribute.
  - [x] allow `[affordance]` HTML attribute to set initial state.
  - [x] drop`[screen and (max-width: 800px)] collapse` media affordance syntax.
  - [x] allow `--affordance` CSS property to set state.
  - [x] watch `--affordance` CSS property.
  - [x] rework shadow parts to internalize the affordances of `collapse`, `exclusive-collapse`, `tab-bar`, and `none`.
  - [x] expose `toggle` events.
  - [ ] update tests according to changes.

- create `pages` branch or directory for sharing on the web that uses the `oui` branch:
  - [x] create installation page
  - [x] create demonstration page(s)
  - [ ] create explainer page(s)

---

**Demo**: https://tabvengers.github.io/spicy-sections/src/
**Branch**: https://github.com/tabvengers/spicy-sections/tree/oui

**Comment by jonathantneal** [comment]
At the final stretch, now. These are the remaining tests:

- [ ] Add tests for public event API.
- [ ] Add tests for unknown affordance.
- [ ] Add tests for broken content.
- content before a heading
  - heading as a last element
  - heading followed by a heading
- [ ] Add tests for when content is dynamically injected into the panelset
- [ ] Add tests for keyboard navigation
